---
title: "Human Performance"
page-layout: full
title-block-banner: true
page-navigation: true
toc: true
toc-title: "Outline"
---

My academic work in neuroscience and spatial statistical modeling developed from sustained involvement in competitive sports. 
Direct exposure to elite athletes and their performance led to a deeper interest in how complex biological systems adapt to training under various physiological and environmental constraints.
This trajectory moved my scientific focus from exercise physiology to neuroscience and ultimately to quantitative modeling in statistics.

Alongside academic training, I have remained engaged in strength and conditioning and athlete development across collegiate and private settings.

<br> 

## Certifications

NSCA Certified Strength & Conditioning Specialist (CSCS) <br> 
USA Weightlifting Level 1 Coach


## Athletic Achievement

USA Modern Pentathlon National Championships (11th) <br> 
Japan Masters Weightlifting National Championships (3rd) <br> 
USA Weightlifting Collegiate National Championships (4th) <br> 
Indiana University Men’s Swimming & Diving (NCAA Division I) <br> 


## Coaching & Leadership

Volunteer Coach, Indiana University, Track & Field (Pole Vault) <br> 
Club Director & Head Coach, Imaginary Unit, USA Weightlifting Club <br> 
Team Coordinator & Head Coach, Counsilman Center Swim Team, USA Swimming Club <br> 
Student Assistant Coach, Indiana University, Men's Swimming & Diving <br> 


## Elite Athlete Development

Strength and conditioning support for post-collegiate athletes.

**World Top 100**

- Track & Field — M Triple Jump (Olympian)
- Track & Field — W Pole Vault
- Track & Field — W Sprint
- Swimming — M Sprint Freestyle

**US Top 100**

- Track & Field — W Distance
- Track & Field — M Decathlon
- Track & Field — M Hammer Throw
- Track & Field — M Shot Put
